#!/bin/bash
#
# run ls with arguments

tmp_file=".checker_tmp_file_$RANDOM"
tmp_filedir="/tmp"
tmp_filepath="$tmp_filedir/$tmp_file"
command="/bin/ls -la $tmp_filedir/"

# clean up
stop_shell
rm -f $tmp_filepath

# create a pseudo random file
touch $tmp_filepath
chmod 761 $tmp_filepath

# send commands
echo "$command" | $SHELL > $OUTPUTFILE
echo "$command" | sh > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
diff $OUTPUTFILE $EXPECTED > $DIFF
if [ -s $DIFF ]; then
	print_ko
	cat $DIFF
else
	print_ok
fi

# clean up
stop_shell
rm -f $tmp_filepath
