#!/bin/bash
#
# simple test with ls to check if the shell can find ls in the PATH

command="ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file

# run command
echo "$command" | "$SHELL" > "$OUTPUTFILE" 2> "$ERROROUTPUTFILE" &
echo "$command" | sh > "$EXPECTED"

# wait a little bit
"$SLEEP" "$SLEEPSECONDS"

# check the result
check_diff

# print error
print_error

# clean up
stop_shell
