#!/bin/bash
#
# run a mix of ls and /bin/ls many times

command="ls
ls
ls
/bin/ls
ls
ls
ls
/bin/ls
ls
ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file

# run command
echo "$command" | "$SHELL" > "$OUTPUTFILE" 2> "$ERROROUTPUTFILE" &
echo "$command" | sh > "$EXPECTED" 2> "$ERROREXPECTED"

# wait a little bit
"$SLEEP" "$SLEEPSECONDS"

# check the result
check_diff

# error
print_error

# clean up
stop_shell
