#!/bin/bash
#
# check if the memcpy function was used by using ltrace

command="/bin/ls
/bin/ls
/bin/ls"

# clean up
stop_shell

# send commands
echo "$command" | ltrace -bcf -o $LTRACEOUTPUTFILE $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $LTRACEOUTPUTFILE | grep memcpy > $DIFF`
check_function

#errors
print_error

# clean up
stop_shell
