#!/bin/bash
#
# run /bin/ls many times, with a lot of spaces everywhere

command="/bin/ls
     /bin/ls
/bin/ls     
  /bin/ls     "
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file

# run command
echo "$command" | "$SHELL" > "$OUTPUTFILE" 2> "$ERROROUTPUTFILE" &
echo "$command" | sh > "$EXPECTED"

# wait a little bit
"$SLEEP" "$SLEEP"SECONDS

# check the result
check_diff

# print error
print_error

# clean up
stop_shell
