#!/bin/bash
#
# Empty the PATH and check if '/bin/ls' still works (with path)

command="/bin/ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file

# empty PATH
OLDPATH="$PATH"
PATH=""

# run command
echo "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &
echo "$command" | sh > $EXPECTED 2> $ERROREXPECTED

# put PATH back
PATH="$OLDPATH"

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

#errors
print_error

# clean up
stop_shell
