#!/bin/bash
#
# Can you set and overwrite env?

command="setenv NEWUSER Elaine
setenv NEWUSER Hunter
setenv NEWUSER Kimberly
env"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file

# run command
echo "$command" | $SHELL > $tmp_file
cat $tmp_file | grep NEWUSER=Kimberly > $OUTPUTFILE 2> $ERROROUTPUTFILE &
echo "NEWUSER=Kimberly" > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

# error
print_error

# clean up
stop_shell
