#!/bin/bash
#
# Can you set env correctly with semicolons?

command="setenv DRWHO We’reallstories,intheend.Justmakeitagoodone,eh?;env"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file

# run command
echo "$command" | "$SHELL" > $tmp_file
cat $tmp_file | grep DRWHO=We’reallstories,intheend.Justmakeitagoodone,eh? > "$OUTPUTFILE" 2> "$ERROROUTPUTFILE" &
echo "DRWHO=We’reallstories,intheend.Justmakeitagoodone,eh?" > "$EXPECTED"

# wait a little bit
"$SLEEP" "$SLEEPSECONDS"

# check the result
check_diff

# error
print_error

# clean up
stop_shell
