#!/bin/bash
#
# Can you unset env?

command="setenv AUSTIN KeepAustinWeird
env
unsetenv AUSTIN
env"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file

# run command
echo "$command" | "$SHELL" > $tmp_file 2> "$ERROROUTPUTFILE" &
cat $tmp_file | grep AUSTIN=KeepAustinWeird > "$OUTPUTFILE"
> "$EXPECTED"

# wait a little bit
"$SLEEP" "$SLEEPSECONDS"

# check the result
check_diff

# error
print_error

# clean up
stop_shell
