#!/bin/bash
#
# exit with status

command="exit 98"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file

# send commands
echo "$command" | "$SHELL"
echo "$?" > "$OUTPUTFILE"
echo "$command" | sh
echo "$?" > "$EXPECTED"

# wait a little bit
"$SLEEP" "$SLEEPSECONDS"

# check the result
check_diff

# print error
print_error

# clean up
stop_shell
