#!/bin/bash
#
# exit with status

command="ls
exit 98"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file

# send commands
echo "$command" | $SHELL > $tmp_file 2> $ERROROUTPUTFILE &
echo "$?" > $OUTPUTFILE
echo "98" > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

# print error
print_error

# clean up
stop_shell
