#!/bin/bash
#
# exit status 1999

command="exit 1999"
# clean up
stop_shell

# create a pseudo random file

# send commands
echo "$command" | $SHELL 2> $ERROROUTPUTFILE &
echo "$?" > $OUTPUTFILE
echo "1999" > $EXPECTED


# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

# print error
print_error

# clean up
stop_shell
