#!/bin/bash
#
# check if a medium size command line does not break the shell

command="                                       /bin/ls                                                                                                                                                                                                                                                                                                                                                                                                                                                     "
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
echo "$command" > $tmp_file

# run command
cat $tmp_file | "$SHELL" > "$OUTPUTFILE" 2> "$ERROROUTPUTFILE" &
cat $tmp_file | sh > "$EXPECTED"

# wait a little bit
"$SLEEP" "$SLEEPSECONDS"

# check the result
check_diff

# print error
print_error

# clean up
stop_shell
