#!/bin/bash
#
# check if the getline function was used by using ltrace

command="/bin/ls
/bin/ls
/bin/ls"

# clean up
stop_shell

# send commands
echo "$command" | $LTRACE -bc -o $LTRACEOUTPUTFILE $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# wait a little bit
$SLEEP $SLEEPSECONDS

#errors
print_error

# check the result
nmatch=`cat $LTRACEOUTPUTFILE | grep getline | wc -l`
if [ $nmatch -eq 1 ]; then
    print_ko
else
    print_ok
fi

# clean up
stop_shell
