#!/bin/bash
#
# Empty the PATH and check if /bin/ls still works

command="/bin/ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file
# empty PATH
OLDPATH="$PATH"
PATH=""

# run command
echo "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &
echo "$command" | sh > $EXPECTED

# put PATH back
PATH="$OLDPATH"

# wait a little bit
$SLEEP $SLEEPSECONDS

cat $ERROROUTPUTFILE

# check the result
diff $OUTPUTFILE $EXPECTED > $DIFF
if [ -s $DIFF ]; then
	print_ko
	cat $DIFF
else
	print_ok
fi

# clean up
stop_shell
