#!/bin/bash
#
# run a mix of ls and /bin/ls many times

command="ls
ls
ls
/bin/ls
ls
ls
ls
/bin/ls
ls
ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file

# run command
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &
echo "$command" | sh > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
diff $OUTPUTFILE $EXPECTED > $DIFF
if [ -s $DIFF ]; then
	print_ko
	cat $DIFF
else
	print_ok
fi

# clean up
stop_shell
