#!/bin/bash
#
# check that the PATH is checked in the right order

command="ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file

# empty PATH
OLDPATH="$PATH"
PATH=":$PATH"

# send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &
$ECHO "$command" | sh > $EXPECTED 2> $ERROREXPECTED

# put PATH back
PATH="$OLDPATH"

# wait a little bit
$SLEEP $SLEEPSECONDS

#error
print_error

# check the result
check_diff

# clean up
stop_shell
