#!/bin/bash
#
# check that the PATH is checked in the right order

command="ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file

# empty PATH
OLDPATH="$PATH"
PATH=":$PATH"

# send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# put PATH back
PATH="$OLDPATH"

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`$CAT $OUTPUTFILE | $GREP -c "$tmp_file"`
if [ $nmatch -eq 0 ]; then
    if [ `$CAT $ERROROUTPUTFILE | wc -c` -ge 5 ]; then
	   print_ok
    else
	   print_ok
    fi
else
    print_ko
fi

# clean up
stop_shell
