#!/bin/bash
#
# run ls with spaces everywhere

command="ls
     ls
ls     
 ls     "
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file

# run command
echo "$command" | $SHELL > $OUTPUTFILE
echo "$command" | sh > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

# clean up
stop_shell
